About
Kriminz/Lighter pull request #27
Opened 2022-12-17 19:15 UTC by Yasinetsky

FIX about img   швидше за все варто заборона використання контектних зображень у секції , швидше за все потрібно використовувати фонові

2022-12-17 19:18 UTC, Kriminz requested changes

2022-12-17 19:18 UTC, Kriminz commented on src/partials/about.html
> +<section class="about container">
container додається на дів

2022-12-17 19:21 UTC, Yasinetsky commented
і ще не зрозуміло ось це (Декоративне зображення з коровою абсолютно спозиціонувати згідно макету.) як його спозиціонувати ,,,,,

2022-12-17 19:24 UTC, Kriminz commented
> FIX about img швидше за все варто заборона використання контектних зображень у секції , швидше за все потрібно використовувати фонові

Треба запропонувати цю ідею в групі аби обговорити, бо можливо зображення в вашій секції і можна використати як фонове

2022-12-17 19:27 UTC, Kriminz commented
> і ще не зрозуміло ось це (Декоративне зображення з коровою абсолютно спозиціонувати згідно макету.) як його спозиціонувати ,,,,,

Через position absolute left 0 bottom 0

2022-12-18 09:43 UTC, Yasinetsky commented
виправив

2022-12-18 10:23 UTC, Kriminz commented
Виправте конфлікт, оновіть мейн, потім свою власну гілку і прйміть зміни. Бо зараз я не можу прийняти ваш пуш

2022-12-18 11:11 UTC, Kriminz approved these changes

2022-12-18 11:20 UTC, merged